id: 8beac993-c7f1-4076-8cf4-90084c4bc2dc
name: Changes to Amazon VPC settings
description: "Amazon Virtual Private Cloud (Amazon VPC) lets you provision a logically isolated section of the AWS Cloud where\
  \ you can launch AWS resources in a virtual network that you define.\nThis identifies changes to Amazon VPC (Virtual Private\
  \ Cloud) settings such as new ACL entries,routes, routetable or Gateways.\nMore information: https://medium.com/@GorillaStack/the-most-important-aws-cloudtrail-security-events-to-track-a5b9873f8255\
  \ \nand AWS VPC API Docs: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/OperationList-query-vpc.html"
owner: security-engineering
status: baseline
kind: Scheduled
severity: Low
enabled: true
query: |-
  let EventNameList = dynamic(["CreateNetworkAclEntry","CreateRoute","CreateRouteTable","CreateInternetGateway","CreateNatGateway"]);
  AWSCloudTrail
  | where EventName in~ (EventNameList)
  | extend UserIdentityArn = iif(isempty(UserIdentityArn), tostring(parse_json(Resources)[0].ARN), UserIdentityArn)
  | extend UserName = tostring(split(UserIdentityArn, '/')[-1])
  | extend AccountName = case( UserIdentityPrincipalid == "Anonymous", "Anonymous", isempty(UserIdentityUserName), UserName, UserIdentityUserName)
  | extend AccountName = iif(AccountName contains "@", tostring(split(AccountName, '@', 0)[0]), AccountName),
    AccountUPNSuffix = iif(AccountName contains "@", tostring(split(AccountName, '@', 1)[0]), "")
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated) by EventName, EventTypeName, RecipientAccountId, AccountName, AccountUPNSuffix, UserIdentityAccountId, UserIdentityPrincipalid, UserAgent,
  UserIdentityUserName, SessionMfaAuthenticated, SourceIpAddress, AWSRegion, EventSource, AdditionalEventData, ResponseElements
  | extend timestamp = StartTimeUtc
queryFrequency: PT1H
queryPeriod: PT1H
triggerOperator: GreaterThan
triggerThreshold: 0
suppressionDuration: PT1H
suppressionEnabled: false
tactics:
- PrivilegeEscalation
- LateralMovement
techniques: []
subTechniques: []
alertRuleTemplateName: 65360bb0-8986-4ade-a89d-af3cf44d28aa
eventGroupingSettings:
  aggregationKind: SingleAlert
createIncident: false
groupingConfiguration:
  enabled: false
  reopenClosedIncident: false
  lookbackDuration: PT5M
  matchingMethod: AllEntities
  groupByEntities: []
  groupByAlertDetails: []
  groupByCustomDetails: []
